### ISSUE TITLE
Before version 2.3, icon can be displayed without picture, but not in the current version?

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#108]
The icon cannot be displayed without picture
![image](https://user-images.githubusercontent.com/58241282/104415560-2bf34b00-55ad-11eb-8b2a-0224dcd4a039.png)

**Comment by gcobb321** [comment]
What is your configuration file for iCloud3?

**Comment by a120578270** [comment]
> What is your configuration file for iCloud3?

The configuration.yaml configuration is
  - platform: icloud3
    username: xxxx
    password: xxxx
    display_zone_format: fname

The config_ic3.yaml configuration is
devices:
  - device_name: iPhone1
    name: xx
    email: xx@qq.com
  - device_name: iPhone2
    name: xxx
    email: 1xxx@qq.com
inzone_interval: 20 min    
max_interval: 45 min    
unit_of_measurement: km

![image](https://user-images.githubusercontent.com/58241282/104417240-04ea4880-55b0-11eb-9ef2-8dbc33bd907b.png)
I just want to use the icon of the original HA, but it doesn't work. In iCloud3 2.3 version, the picture configuration can only be used to appear. May I ask how to solve it?

**Comment by gcobb321** [comment]
When you post code, you should put it in a code block to show the spacing and format. You highlight the code and select the <> formatting code above the area you type in.  

In code block:
```
devices:
  - device_name: gary_iphone
    name: Gary
    email: gary_456@email.com
    picture: gary.png
  - device_name: lillian_iphone
    name: Lillian
    email: lillian_789@email.com
    picture: lillian.png
```

Not in code block:
  - device_name: gary_iphone
    name: Gary
    email: gary_456@email.com
    picture: gary.png
  - device_name: lillian_iphone
    name: Lillian
    email: lillian_789@email.com
    picture: lillian.png
