### ISSUE TITLE
iCloud3 2.3 zone name

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3#109]
Hi, I just installed 2.3 and found an issue with how zones are displayed. I have a zone called “Alysa’s House” and even though I have the format set to fname it displays it as “Alysa S House”

I’ve also tried title and that didn’t work either. How do I get icloud3 to stop messing with my zone name?

My config_ic3.yaml file. Configuration only has username/password
```
devices:
  - device_name: brians_iphone
  - device_name: brians_apple_watch
    noiosapp: True
  - device_name: britnis_iphone
  - device_name: britnis_apple_watch
    noiosapp: True
display_zone_format: fname 
```
