### ISSUE TITLE
Home Assistant Logs being filled with failed calls to the see service

### ISSUE THREAD

**Issue by EvanGrote** [gcobb321/icloud3#120]
As the title says, my Home Assistant logs are being filled with failed calls to the see service every few seconds:
```
2021-02-10 14:35:04 ERROR (MainThread) [homeassistant.components.device_tracker] The see service is not supported for this entity device_tracker.evans_iphone
```

I think this may just be a configuration issue, but I've read through the configuration documentation a few times and I'm still not sure why this is happening. The issue seems to be in some way rooted to being in my home zone or the distance from home zone, because I'm seeing these errors every few seconds when I'm at home, but they occur significantly less often when I am outside my home zone.

All icloud3 functionality appears to be unaffected, but I'd like to root out the cause of these error messages so my Home Assistant logs are not cluttered by thousands of the same error.

----

`configuration.yaml`:
```
device_tracker:
  - platform: icloud3
    username: <apple_account_email>
    password: <apple_account_password>
```

----

`config_ic3.yaml`:
```
devices:
  - device_name: Evans-iPhone
    iosapp_suffix: _ha_app
  - device_name: Clarices-iPhone
    noiosapp: true
max_interval: '5 min'
inzone_interval: '5 min'
stationary_inzone_interval: '5 min'
```
