### ISSUE TITLE
No Devices found after upgrading to 2.3.2

### ISSUE THREAD

**Issue by garyt72** [gcobb321/icloud3#122]
After upgrading from v2.3 to v2.3.2 I get the following errors:
Edit: After upgrading from _v2.3.1_ to v2.3.2 I get the following errors.

```
2021-02-12 18:07:09 ERROR (SyncWorker_10) [custom_components.icloud3.device_tracker] cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/srv/hass/conf/custom_components/icloud3/device_tracker.py", line 8785, in _decode_config_ic3_file
    success_msg, error_msg = self._set_parameter_item(parameter_list_name, parameter_list)
TypeError: cannot unpack non-iterable NoneType object
2021-02-12 18:07:13 ERROR (SyncWorker_10) [custom_components.icloud3.device_tracker]  iCloud3 Error for username@server.com > No devices to track. Setup aborted. Check `track_devices` parameter and verify the device name matches the iPhone Name on the `Settings>General>About` screen on the devices to be tracked.
```

Hoping the first error could be ignored, I tried to work on the 2nd error.  I've tried adding the new name instead of the entity name, but the name on my phone is "Gary's iPhone".  I've had no luck with with any of the following attempts.

original/old value:
```
track_devices:
  - device_name: garys_iphone
```
quoted:
```
track_devices:
  - device_name: "Gary's iPhone"
```
unqouted:
```
track_devices:
  - device_name: Gary's iPhone
```

I do see all of my devices listed in the items found in the Find My app, and they all also listed for devices found for the IOS app.

I've reverted back to v2.3.1 (instead of going back to v2.3) and things are working again.  I'm running Home Assistant Core v2021.2.3 on Ubuntu 18.04 LTS.

**Comment by gcobb321** [comment]
Change `track_devices `to `devices`. 

Example configuration:
```
devices:
  - device_name: Gary’s iPhone
    email: gary_456@email.com
    name: Gary
    picture: gary.png
  - device_name: lillian_iphone
    email: lillian_789@email.com
    name: Lillian
    picture: lillian.png
```

**Comment by garyt72** [comment]
I apologize, the examples above were from one of the attempts to try multiple things.  Per the error message, I tried changing things back from `devices` to `track_devices` and eventually back to `devices` again..  This is my current config that is working for v2.3.1 but failing for v2.3.2 - still using the entity name instead of the name from Settings > General > About.

```
devices:
  - device_name: garys_iphone
    name: Gary
    iosapp_suffix: _iosappv2
  - device_name: brandon_s_iphone
    name: Brandon
    iosapp_suffix: _iosappv2
    track_from_zone: zone.brandon_s_house
  - device_name: jordyn_s_iphone
    name: Jordyn
    iosapp_suffix: _iosappv2
```

**Comment by Triflorseyan** [comment]
I have exactly the same issue. Didn't change anything in the configuration, but after the update, the entities disappeared! 

```
Configuration.yaml
#icloud3 parameters
device_tracker:
  - platform: icloud3
    username: fl...........1@........com
    password: !secret icloud3-pw

Config_ic3.yaml
  devices:
  - device_name: florian_iphonexr
    email: fl...........1@........com
    name: Florian
    picture: /local/pictures/flo.png
  - device_name: Petra's iPhone
    email: p..............@.............com
    name: Petra
```
