### ISSUE TITLE
Internal error after update

### ISSUE THREAD

**Issue by mbucari-code** [gcobb321/icloud3#125]
Hi,
after updating to the latest version, i have this error for all the device tracked

►INTERNAL ERROR-RETRYING (_update_device_icloud:DetInterval-float() argument must be a string or a number, not `NoneType`)

my configuration is

```
configuration.yaml
device_tracker:
  - platform: icloud3
    username: !secret icloud_marco_user 
    password: !secret icloud_marco_pwd

config_ic3.yaml
devices: 
  - device_name: iphone_marco 
    name: Marco
    picture: /local/images/marco.jpg
    track_from_zone: Regione
  - device_name: iphone_silvia 
    name: Silvia
    picture: /local/images/silvia.jpg
    track_from_zone: Crass
    
unit_of_measurement: km
waze_region: EU
waze_realtime: True
```
