### ISSUE TITLE
custom cards

### ISSUE THREAD

**Issue by ronniebee** [gcobb321/icloud3#14]
Hi, as a newbee I'm trying to set up icloud3 (great work btw). I think it's up and running but the custom cards are a pain... 

when I add in de yaml file i get:

![image](https://user-images.githubusercontent.com/7029899/71203160-ccd5e080-229d-11ea-8bee-01c1f9e780bb.png)
What am I doing wrong:

The card is placed in the www/custome_cards directory. Can you pls advise?

also when iI try to make a manual card i get: 
With and without the ident between : icloud and :icloud

![image](https://user-images.githubusercontent.com/7029899/71245029-18c36c80-2314-11ea-806a-43640af1b91e.png)

![image](https://user-images.githubusercontent.com/7029899/71245147-65a74300-2314-11ea-8d4d-3c78b427af36.png)

![image](https://user-images.githubusercontent.com/7029899/71203603-9056b480-229e-11ea-9014-b2efccc0b04e.png)

the file is there.

I get an empty screen:

![image](https://user-images.githubusercontent.com/7029899/71245312-b61ea080-2314-11ea-9787-60c00a10a0d0.png)

Please can you advice this newbee

**Comment by gcobb321** [comment]
It looks like there might be an extra space in the example in the documentation on the lines after the ‘- title’ line. This is copied from my ui-Lovelace.yaml. Try it and see if it works.

```
  - title: iCloud Event Log
    icon: mdi:information-outline 
    cards: 
      - type: custom:icloud3-event-log-card
        entity: sensor.icloud3_event_log

```
I’ll update the docs to correct this.
