### ISSUE TITLE
The see service is not supported for this entity device_tracker.

### ISSUE THREAD

**Issue by niceboygithub** [gcobb321/icloud3#147]
The HA logs continue to log 'The see service is not supported for this entity device_tracker.xxxxx' 

My HA was install in a old Mac Mini.

/Users/username/.homeassistant/congfiguration.yaml
```
device_tracker:
  - platform: icloud3
    username: tlxxxx@me.com
    password: !secret tlxxxx_password
    config_ic3_file_name: /Users/username/.homeassistant/config_ic3.yaml
    entity_registry_file_name: /Users/username/.homeassistant/.storage/core.entity_registry
    exclude_sensors: zont,batstat,lzonn,lzont,name
```

/Users/username/.homeassistant/config_ic3.yaml
```
# --Track Devices Parameters-------------------------------
devices:
  - device_name: fei_de_iphonese
    name: Username
    email: devxxxxxxxx@icloud.com
```
