### ISSUE TITLE
documentation error:  name1 should be name in example

### ISSUE THREAD

**Issue by GHSTUDIO1** [gcobb321/icloud3#168]
I don't believe name1 should just be name in the following example from the documentation:
```
#   Gary leaves a zone
#--------------------------------------------------------------
 - alias: Gary Leaves Zone
   id: gary_leaves_zone
   trigger:
     - platform: state
       entity_id: sensor.gary_iphone_zone_name1
       to: 'Away'
```
