### ISSUE TITLE
Findmy friends no longer working

### ISSUE THREAD

**Issue by hijamie32** [gcobb321/icloud3#172]
Hi

I am having an issue with this since I think iCloud was updated to iCloud+.

Now it no longer finds any findmy friends email accounts?

Was working fine before

Is anyone else having this issue.

Thanks

Jamie

**Comment by Snuffy2** [comment]
Same issue. It seems to now only be showing users who have upgraded to iOS 15.

**Comment by gcobb321** [comment]
With the release of iOS 15 (9/21/2021), the url used to access the Apple iCloud Find-My-Friends (FmF) is no longer being returned by Apple when signing on to the account. The Family Sharing (FamShr) url is still being returned. 

The FmF tracking method is no longer available until it can be determined how to access the FindMy friends data. Until this problem is solved, you will have to use the Family Sharing tracking method.

**Comment by miraixyz** [comment]
I am not sure if this is related, but after switching to fmshr because of the above mentioned issue, my picture no longer displayed.  It worked perfectly before and all I changed was the tracking method. My configuration.yaml:

```
device_tracker:  
  - platform: icloud3
    username: username@gmail.com
    password: !secret icloud3_pw
    tracking_method: famshr
    track_devices: 
      - myiphone > /local/me.jpg
```

**Comment by miraixyz** [comment]
Found my problem....seems that changing the tracking method also changes the entity name...at least it did for me.  So the picture that was associated with my iphone wasn't showing because my front end wasn't displaying the correct device entity name.

**Comment by gcobb321** [comment]
Glad you found it. 

BTW-iCloud3 v2.4 also depreciated the *track_devices* parameter and replaced it with the *devices* parameter.

```
devices:
  - device_name: myiphone
    picture: /local/me.jpg
    name: Me
    email: me@email.com
```
The full description is [here](https://gcobb321.github.io/icloud3/#/chapters/1.6-configuring-starting-icloud3?id=the-configuration-files-configurationyaml-and-config_ic3yaml).
