### ISSUE TITLE
Feature request: min_interval

### ISSUE THREAD

**Issue by andreasgily** [gcobb321/icloud3#178]
Hi Gary,

We are using the FamilySharing option, in our family (4 devices). Especially when all devices are near the home zone, we experience quite a battery draining issue on our iPhones. 

Are the update intervals all synced (every single device fires every 15 seconds, so if you have 4 devices this can trigger quite a lot of icloud location updates)?

What about an option for a global "min_interval" limit (to e.g. set it to 5 minutes instead of pinging all devices every 15 seconds)

cheers,
Andreas

**Comment by pauly7300** [comment]
Where are you seeing evidence of updates every 15 seconds?  See here for the configuration parameters and how update intervals are calculated.  https://gcobb321.github.io/icloud3/#/chapters/2.1-config-parms?id=zone-interval-and-sensor-configuration-items.

Have you created any zones other than the default home?  The calculation for updates is different when devices are in a zone or outside.  Also see the travel_time_factor on the link above to understand how the update frequency is changed dynamically as the device is further (longer frequency) or closer (more frequent) away from home.

inzone_interval
The interval between location updates when the device is in a zone. This can be in seconds, minutes or hours, e.g., 30 secs, 1 hr, 45 min, or 30 (minutes are assumed if no time qualifier is specified).
Default: 2 hrs

Generally speaking, you would need to alter the default config settings in order to get an update frequency as low as you're reporting.  You might also check on the devices under settings>battery and the 'usage by app' just to see if there are other apps that might be using more battery than expected.

**Comment by amaisano** [comment]
Is it possible to set an interval ONLY for an Apple Watch, and not for all iCloud devices on the account? I need to monitor my Watch for charging/not-charging in a 1 minute interval, but this drains my iPhone very quickly, even though I don't need that data for my iPhone...

**Comment by gcobb321** [comment]
Yes. Each device can have it's own `inzone_interval` so you can set the interval for the watch to one value while using another value for other devices. The other devices will use the standard inzone interval. 

See docs [here](https://gcobb321.github.io/icloud3/#/chapters/2.1-config-parms?id=inzone_intervals) for more info on inzone intervals.
```
devices:
  - device_name: gary_iphone
    email: gary_456@email.com
    name: Gary
    picture: gary.png
  - device_name: lillian_watch
    email: lillian_789@email.com
    name: LillianW
    picture: lillian.png
    inzone_interval: 1 min              <======= inzone interval
```
