### ISSUE TITLE
INTERNAL ERROR-RETRYING

### ISSUE THREAD

**Issue by poudenes** [gcobb321/icloud3#180]
Hi There,

HA: 2021.9.7
Debain 64Bit

After the latest update to: 2.4.5 I get these errors.

```
-- sys event --	6:04:10p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:15p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:16p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:20p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:25p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:30p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:31p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:35p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:40p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:45p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:46p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:50p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
-- sys event --	6:04:55p	-	-	-	-	-	►INTERNAL ERROR-RETRYING (_determine_interval:SetupZone-can`t multiply sequence by non-int of type `float`)
```

**Comment by gcobb321** [comment]
I looked at the code and there are 2 multiple statements in that routine. The error doesn’t make sense because all the values should be numbers.  However, I just uploaded v2.4.6 to the development directory of the iCloud3 repository with some error checking to catch the errors when they happen. It also contains changes for the cellphone icon and a few other things. Download that and see if those errors go away and everything looks ok. If it does, let me know and I’ll update HACS.

**Comment by poudenes** [comment]
Errors are still there.

**Comment by poudenes** [comment]
Here my config file, maybe there I something wrong:

I now removed all the " " and check it again

```
devices:
  - device_name: "peter_iphone"
    name: "Peter"
    picture: "local/images/person/peter-home.png"

  - device_name: "cenkay_13"
    picture: "local/images/person/kay-home.png"
    name: "Kay"
    iosapp_installed: false

###########################################################################################
# General Parameters
###########################################################################################
event_log_card_directory: "/log"
unit_of_measurement: km

###########################################################################################
# Zone/Tracking Parameters
###########################################################################################
inzone_interval: "2 hrs"
max_interval: "4 hrs"
center_in_zone: false
stationary_inzone_interval: "30 min"
stationary_still_time: "8 min"
stationary_zone_offset: (52.328677, 4.853867)
travel_time_factor: ".6"

###########################################################################################
# Accuracy Parameters
###########################################################################################
gps_accuracy_threshold: "125"
ignore_gps_accuracy_inzone: true
old_location_threshold: "2 min"

###########################################################################################
# Waze Parameters
###########################################################################################
distance_method: waze
waze_region: EU
waze_min_distance: 1
waze_max_distance: 1000
waze_realtime: true
```
