### ISSUE TITLE
config_ic3_file_name Config Bug / Enhancement Request

### ISSUE THREAD

**Issue by Colorado4Wheeler** [gcobb321/icloud3#188]
This could be intentional, and if it is then this is an enhancement request, if it is not then this is a bug :).

When using relative paths in the device_tracker file iCloud3 will bomb saying it cannot find the file.  However, if the full system path is used then it works fine.

For example:

```
device_tracker:
  - platform: icloud3
    username: !secret icloud_username
    password: !secret icloud_password
    config_ic3_file_name: ../entities/hacs_icloud3/config_ic3.yaml
```

Will not work, resulting in an error:

![Screen Shot 2021-12-24 at 8 27 21 AM](https://user-images.githubusercontent.com/20329385/147371504-ac5ca562-aef5-44c3-8163-a631601dd254.png)

But, the full system path works fine:

```
device_tracker:
  - platform: icloud3
    username: !secret icloud_username
    password: !secret icloud_password
    config_ic3_file_name: /config/entities/hacs_icloud3/config_ic3.yaml
```

In my configuration I load device_tracker.yaml from a subfolder of /config/integrations/device_tracker.yaml rather than from the default folder of /config/device_tracker.yaml.

Home Assistant: 2021.12.5
Installed iCloud3: 2.4.6
