### ISSUE TITLE
Error when starting icloud3 - No setup or config entry setup function defined.

### ISSUE THREAD

**Issue by twinkie0101** [gcobb321/icloud3#189]
Got this error message but can see the log populating so not sure if I should be worried about this or not.  Here is the message:

```
Logger: homeassistant.setup
Source: setup.py:153
First occurred: 10:28:07 PM (1 occurrences)
Last logged: 10:28:07 PM

Setup failed for icloud3: No setup or config entry setup function defined.
```
Here is my config.yaml and ic3.yaml info

config yaml:

```
icloud3:
device_tracker:
  - platform: icloud3
    username: email
    password: pw
    create_sensors: zon,zonn,ttim,zdis,cdis,wdis,nupdt,lupdt,info`
    exclude_sensors: zont,zonfn,lzont,lzonfn,zonts,bat
    event_log_card_directory: 'www/custom_cards'
    config_ic3_file_name: '/config/config_ic3.yaml'
    tracking_method: iosapp
```

ic3 yaml:
```
devices:
    - device_name: Scott-iPhone
      name: Scott
      iosapp_installed: True 
    - device_name: Trudy-iPhone
      name: Trudy
      iosapp_installed: True
      
  #-- Formatting Parameters---------------------------------------
  unit_of_measurement: mi
  time_format: 12
 
  display_zone_format: name
  display_text_as:
    - email > scott-email@email.com
    - email > trudy-email@email.com

  #--Zone/Tracking Parameters-----------------------------------------
  inzone_interval: '60 min'
  max_interval: '4 hrs'
  center_in_zone: True
  stationary_inzone_interval: '30 min'
  stationary_still_time: '8 min'
  stationary_zone_offset: 1, 0
  travel_time_factor: .6
  distance_method: waze

  #--Accuracy Parameters-------------------------------------
  gps_accuracy_threshold: 100
  ignore_gps_accuracy_inzone: True
  old_location_threshold: '2 min'

  #--Waze Parameters-----------------------------------------
  waze_region: US
  waze_min_distance: 1
  waze_max_distance: 9999
  waze_realtime: True

  #-- Debug/Logging Parameters---------------------------------------
  log_level: debug
```

Thanks for your insight!
