### ISSUE TITLE
Activity Tracking Consistently Showing as Unknown

### ISSUE THREAD

**Issue by twinkie0101** [gcobb321/icloud3#191]
In my ic3 config yaml I have the following:

```
devices:
    - device_name: Name-iPhone
      name: Name
      iosapp_installed: True
```
My status consistently shows as 'unknown' when stationary.  

In the HA app I have zone enter/exit, background fetch, significant location change, and push notifications all turned on.  Sensors are set to update every minute.  

If change iosapp_installed: False the status registers as stationary.  The status does appear to properly obtain walking and automotive.

Any idea on what could be causing this?

If I leave the iosapp_installed: False but use the app, will that break the integration?  I haven't tried reinstalling the app, so maybe that's an option?

My wifes' phone is working as expected.
