### ISSUE TITLE
Tracking Paused - excessive errors encountered

### ISSUE THREAD

**Issue by JeroenTuinstra** [gcobb321/icloud3#248]
I have a apple watch and an iphone that are used with iCloud3. I am only using it to get the battery status of the watch. However this information is blocked very often because tracking has been paused by excessive errors. 

No clue why this is happening. I read the explanation that the integration thinks that the device is no longer online. That is 100% not the case and constant 4g connection or wifi (with fast speeds). 

I did read this though: 

![Screenshot 2023-01-10 003539](https://user-images.githubusercontent.com/47460053/211429432-50fd3fc0-9aed-47e4-b465-b9d792dae28d.png)

So the location is discarded when it is -100m till 200m. I work very close to where I live, possibly less than 200 meters away. How can I stop it from discarding the location. As you can see it discards it 401 times and requests 405 times form icloud.

At this point it is very annoying as some of my automations are depending on the battery level of the watch and that just stops working without warning.

**Comment by gcobb321** [comment]
The location time is monitored and when the device is close to the zone, the old location threshold can be small. Plus, if you are on 4g, the time it takes Apple to get and then report the location can take a while. Try using ‘old_location_threshold: xx min‘ parameter to increase it. Tracking Watches can be a problem since they don’t seem to be able to respond to location requests as fast as a phone. They also seem to be better passing location info through a phone, even though they have cell capabilities.

**Comment by bishop8472** [comment]
I have the same issue. Within a day of rebooting Home Assistant or iCloud3 my iPhone, my wife's and later my two kid's iPads become PAUSED. I have no clue why this is because it used to work fine in the past. Only had this problem a few times.

My iPhone has the HA Companion app and my wife's has not. I am using this to track and predict if we're on our way home. This is mainly used to start heating the livingroom in the winter.

code:
```
# --Zone/Tracking Parameters--------------------------------
  inzone_intervals:
    - inzone_interval: 1 hrs
    - ipad: 2 hrs
    - watch: 30 min
    - no_iosapp: 30 min

# --Display Parameters--------------------------------------
  display_zone_format: fname #was title
  unit_of_measurement: km
  time_format: 24

# --Accuracy Parameters-------------------------------------
  gps_accuracy_threshold: 250
  ignore_gps_accuracy_inzone: True
  old_location_threshold: 60

# --Waze Parameters-----------------------------------------
  distance_method: waze
  waze_region: EU
  waze_realtime: True
```

I've tried various settings for "old_location_threshold:" but it does not seem to matter.
