### ISSUE TITLE
Phone which is turned off gets polled with an interval of 0

### ISSUE THREAD

**Issue by riemers** [gcobb321/icloud3#40]
The wife has her phone disabled, either turned off or airplane mode. It keeps polling the phone and the interval is set to 0 sec. Because it keeps retriggering that often the phone doesn't get a chance to report back its offline it seems because the spinner keeps going if i look on the find my iphone app.

![image](https://user-images.githubusercontent.com/682041/57888378-4dc58900-7832-11e9-861a-37a344b8a11b.png)

Keeps polling like crazy, but it doesn't update anything anymore. Her status is currently 'away' but since its turned off it keeps trying.

**Comment by gcobb321** [comment]
If the device is turned off, in airplane mode or disabled, the device can not be found by the iCloud location service so it reports an error with no location information, thinks it is just in a dead area and keeps retrying.  The poll count of 0:0:716 says that 0 updates were from the iCloud service, 0 updates were from the ios app and 716 errors were reported. You can also tell the device is offline by the "Old Location #715 (*the error count*), Age 98.4 min (*the time since a last valid location*).

I will look at adding a limit to the error count and automatically pause the polling if this happens. 

Meanwhile, you can pause the polling of the phone by issuing an icloud_update service call with a pause command. The iCloud3 documentation for this is [here](https://github.com/gcobb321/icloud3#icloud_update-service------control-how-icloud3-operates). The script for doing this is:
```
icloud_command_pause_polling_gary:
  alias: 'Pause (Gary)'
  sequence:
    - service: device_tracker.icloud_update
      data:
        device_name: gary_iphone
        command: pause
```
