### ISSUE TITLE
Authentication expired automation

### ISSUE THREAD

**Issue by SoCuul** [gcobb321/icloud3#439]
How would I go about setting up an automation to run when my icloud3 authentication expires?

Currently it is just left unauthenticated until I check the hass app, which is sub-optimal.

**Comment by gcobb321** [comment]
A message is displayed at the top of the _Event Log_ when an authentication is needed. I believe it is also in the _alerts_ attribute of the _sensor.icloud_event_log_ entity. You might be able to set up an automation trigger using that. Request a new code, which j will display the authentication is needed message and fill in the alert attribute. 

Then enter the code to clear the message and attribute

**Comment by SoCuul** [comment]
If anyone else wants to have the same type of automation, feel free to use this one:
```yaml
alias: iCloud3 requires authentication
triggers:
  - trigger: time_pattern
    hours: "*"
conditions:
  - condition: template
    value_template: >-
      {{ state_attr('sensor.icloud3_event_log', 'alert') is
      match(".*Authentication Needed.*", ignorecase=True) }}
    alias: If iCloud3 requires authentication
actions:
mode: single
```

**Comment by gcobb321** [comment]
This will change in v3.2.3. The _Event Log_ alert attributes have been depreciated and replaced with the _icloud3_alerts_ sensor. 

See the iCloud3 docs [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/1as-icloud3-alerts-sensor) for more info and some example automations.

**Comment by SoCuul** [comment]
Updated my automation :)

```yaml
alias: iCloud3 requires attention
description: ""
triggers:
  - trigger: time_pattern
    hours: "*"
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.icloud3_alerts
        attribute: message_text
        for:
          hours: 0
          minutes: 5
          seconds: 0
        state: ""
        alias: iCloud3 has an alert message for 15 minutes
actions:
mode: single
```
