### ISSUE TITLE
Can the integration expose a sensor or similar when it has stopped working due to needing re-authentication?

### ISSUE THREAD

**Issue by ChrisJ60** [gcobb321/icloud3#452]
From time to time it seems that re-authentication with Apple is required, particularly sometimes after restarting HA. It's easy to not be aware of this until things start to break. If the integration could expose a sensor to indicate that it requires re-authentication then an automation could alert the user allowing them to take corrective action sooner rather than later.

**Comment by gcobb321** [comment]
The sensor.icloud3_event_log has several 'alert' attributes that can be monitored. When an authentication is needed, a message is displayed in the _Event Log_ and added to the 'alert' attribute. Set up an automation to send yourself. Message when that changes. 

One is use that monitors all of them is:


```
alias: iCloud3 Alert Message (All)
description: Send an Alert Msg (All Alerts)
triggers:
  - entity_id:
      - sensor.icloud3_event_log
    attribute: alerts
    for:
      hours: 0
      minutes: 0
      seconds: 0
    trigger: state
conditions: []
actions:
  - data_template:
      title: iCloud3 Alert Summary
      message: "{{ state_attr('sensor.icloud3_event_log', 'alerts') }}"
    action: script.notify_gary_iphone
  - data_template:
      title: iCloud3 Startup Alerts
      message: "{{ state_attr('sensor.icloud3_event_log', 'alert_startup') }}"
    action: script.notify_gary_iphone
  - data_template:
      title: iCloud3 Tracked Devices Alerts
      message: "{{ state_attr('sensor.icloud3_event_log', 'alert_tracked') }}"
    action: script.notify_gary_iphone
  - data_template:
      title: iCloud3 Monitored Devices Alert
      message: "{{ state_attr('sensor.icloud3_event_log', 'alert_monitored') }}"
    action: script.notify_gary_iphone
mode: single
```
