### ISSUE TITLE
icloud family - not all devices listed

### ISSUE THREAD

**Issue by kongolml** [gcobb321/icloud3#65]
- homeassistant: 0.98.5
- icloud3: 1.0.6
- master icloud account: icloudaccount
- master iphone name/homeassistant device id: **kostya**
- wife's iphone name/homeassistant device id: **wife**
- **kostya** icloud accont is master account for apple family (containing my iphone, wife's iphone and 4 more iphones, which will not use homeassistant)
- homeassistant have 2 users: **Kostya** and **Wife**

im trying to setup system for 2 users: **kostya** and **wife**.

configuration.yaml:
```yaml
device_tracker:
  - platform: icloud3
    username: !secret master_icloud_email
    password: !secret master_icloud_password
    account_name: kostiantyn (this is my icloud first name)
    include_device_type: iphone
    exclude_devices:
      - iphone1
      - iphone2
      - iphone3
    distance_method: calc
    unit_of_measurement: km
```

known_devices.yaml
```yaml
kostya:
  hide_if_away: false
  icon:
  mac: !secret my _phone _mac
  name: Kostya
  picture:
  track: true

iphone1: ...
iphone2: ...
etc..
```
here is my current state of my device in device_tracker:
```json
{
  "source_type": "gps",
  "latitude": "my home value, even thought im not home, but in other zone currently",
  "longitude": "my home value, even thought im not home, but in other zone currently",
  "gps_accuracy": 0,
  "zone": "not_set",
  "last_zone": "not_set",
  "zone_timestamp": "",
  "trigger": "",
  "timestamp": "2019-09-18T11:32:21.919",
  "interval": "",
  "travel_time": "",
  "distance": 0,
  "calc_distance": 0,
  "waze_distance": 0,
  "last_located": "00:00:00",
  "last_update": "00:00:00",
  "next_update": "00:00:00",
  "poll_count": "0:0:0",
  "dir_of_travel": "",
  "travel_distance": 0,
  "info": "",
  "speed": 0,
  "speed_high": 0,
  "speed_average": 0,
  "altitude": 0,
  "battery_status": "",
  "device_status": "",
  "low_power_mode": "",
  "authenticated": "",
  "tracking": " kostya",
  "alias": "kostya",
  "icloud3_version": "1.0.6",
  "event_log": "",
  "friendly_name": "Kostya"
}
```

the problems i have are:

1. known_devices.yaml **doest not** contain wife's device, even though she is logged in her homeassistant account (device id: **wife**) - so obviously its not being tracked
2. **kostya** state is mostly in state "Not set"

in homeassitant logs i only have `You are using a custom integration for icloud3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.`
